const assert = require('node:assert/strict');
module.exports = async function testMemory(client) {
    const m = client.memory;
    const weights = { keyword: .35, vector: .5, recency: .1, importance: .05 };
    assert.equal(await m.create('hybrid', { dim: 2, metric: 'L2', weights, halflife: 100 }), 'OK');
    assert.equal(await m.config('hybrid', { halflife: 200, weights }), 'OK');
    const info = await m.info('hybrid');
    assert.equal(info.mode, 'HYBRID'); assert.equal(info.dim, 2);
    assert.equal(info.halflife, 200); assert.deepEqual(info.weights, weights);
    assert.equal(await m.add('hybrid', { id: 'a', text: 'database preference', vector: [1, 0], meta: { kind: 'preference', n: 2 }, importance: .8, ttl: 30, condition: 'NX' }), 'a');
    const record = await m.get('hybrid', 'a', { withMeta: true, withVector: true });
    assert.equal(record.text, 'database preference'); assert.equal(record.importance, .8);
    assert(record.created_at > 0); assert(record.updated_at > 0); assert(record.pttl > 0);
    assert.equal(record.meta.get('kind'), 'preference'); assert.deepEqual([...record.vector], [1, 0]);
    assert.equal(await m.card('hybrid'), 1);
    assert.equal(await m.get('hybrid', 'missing'), null);
    assert.equal((await m.mget('hybrid', 'a', 'missing'))[1], null);
    assert.equal((await m.get('hybrid', 'a', { noText: true })).text, undefined);
    assert.equal(await m.setMeta('hybrid', 'a', new Map([['extra', 'yes']])), 1);
    assert.equal(await m.delMeta('hybrid', 'a', 'extra'), 1);
    assert.equal(await m.expire('hybrid', 'a', 0), true);
    assert.equal((await m.get('hybrid', 'a')).pttl, -1);
    assert.equal(await m.expire('hybrid', 'missing', 10), false);
    const scan = await m.scan('hybrid', '0', { count: 10, filters: [{ field: 'kind', op: 'EQ', value: 'preference' }] });
    assert.equal(scan.cursor, '0'); assert.deepEqual(scan.ids, ['a']);
    const options = { topK: 1, withMeta: true, withVector: true, withScores: true, filters: [{ field: '@importance', op: 'GTE', value: .5 }] };
    for (const hits of [await m.search('hybrid', 'database', options), await m.vsearch('hybrid', new Float32Array([1, 0]), options), await m.query('hybrid', { text: 'database', vector: [1, 0], fusion: 'RRF', weights, ...options })]) {
        assert.equal(hits.length, 1); assert.equal(hits[0].id, 'a');
        for (const field of ['score', 'keyword_score', 'vector_score', 'recency_score']) assert.equal(typeof hits[0][field], 'number');
        assert.deepEqual([...hits[0].vector], [1, 0]); assert.equal(hits[0].meta.get('kind'), 'preference');
    }
    await assert.rejects(m.add('hybrid', { id: 'a', text: 'duplicate', condition: 'NX' }), /existence/);
    await assert.rejects(m.add('hybrid', { text: 'bad dimension', vector: [1] }), /dimension/);
    await assert.rejects(m.add('hybrid', { text: 'bad float', vector: [NaN, 0] }), /NaN|infinity/);
    await assert.rejects(m.info('missing'), /no such/);
    await client.set('wrong', 'type'); await assert.rejects(m.card('wrong'), /WRONGTYPE/);
    assert.equal(await m.add('hybrid', { id: 'a', text: 'updated database', vector: [0, 1], condition: 'XX' }), 'a');
    assert.equal(await m.del('hybrid', 'a', 'missing'), 1);
    assert.equal(await m.card('hybrid'), 0);
    await m.create('search', { mode: 'SEARCH' });
    const generated = await m.add('search', { text: '' }); assert.equal(typeof generated, 'string');
    assert.equal((await m.get('search', generated, { withVector: true })).vector, null);
    await assert.rejects(m.vsearch('search', [1, 0]), /no vectors/);
    await m.create('vector', { mode: 'VECTOR', dim: 2, metric: 'IP' });
    const bytes = Buffer.alloc(8); bytes.writeFloatLE(1, 0); bytes.writeFloatLE(.5, 4);
    await m.add('vector', { text: 'vector', vector: bytes });
    assert.equal((await m.query('vector', { vector: bytes, fusion: 'LINEAR' })).length, 1);
    const b = client.memoryBuffer;
    const id = Buffer.from([255, 0, 128]), field = Buffer.from([254, 0]), value = Buffer.from([253, 128]);
    assert.deepEqual(await b.add('search', { id, text: value, meta: new Map([[field, value]]) }), id);
    const binary = await b.get('search', id, { withMeta: true });
    assert.deepEqual(binary.id, id); assert.deepEqual(binary.text, value);
    assert.deepEqual([...binary.meta], [[field, value]]);
    assert.deepEqual((await b.mget('search', id))[0].id, id);
    assert((await b.scan('search', 0)).ids.every(Buffer.isBuffer));
    await assert.rejects(m.mget('search'), /At least/);
    await assert.rejects(m.setMeta('search', id, {}), /At least/);
};
